services:
  - type: web
    name: gestion-stock
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: gestion-stock-db
          property: host
      - key: DB_DATABASE
        fromDatabase:
          name: gestion-stock-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: gestion-stock-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: gestion-stock-db
          property: password

databases:
  - name: gestion-stock-db
    databaseName: gestion_stock
    user: laravel